version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      mongo-init:
        condition: service_completed_successfully
      mongodb:
        condition: service_started

  mongodb:
    image: mongo:6.0
    container_name: mongodb-gdash
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - '27017:27017'
    env_file:
      - ./backend/.env
    environment:
      - USERNAME=${MONGO_USERNAME}
      - PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  mongo-init:
    image: mongo:6.0
    container_name: mongo-init
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    command: >
      mongosh --host mongodb:27017 --eval 
      '
      try {
        rs.status();
        print("Replica Set já inicializado.");
      } catch (e) {
        rs.initiate({ _id: "rs0", members: [{ _id: 0, host: "mongodb:27017" }] });
        print("Replica Set inicializado com sucesso.");
      }
      '
  weather-service:
    build: 
      context: ./weather-service
    container_name: python-weather-service
    depends_on:
      - rabbitmq 
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest 
      - RABBITMQ_PASS=guest
      - LATITUDE=-15.8973
      - LONGITUDE=-52.2301
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-gdash
    ports:
      - "5672:5672" 
      - "15672:15672" 
    networks:
      - app-network

  go-worker:
    build:
      context: ./go-worker
    container_name: go-weather-worker
    depends_on:
      - rabbitmq
      - backend
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - API_URL=http://nest-backend:3000/api/weather/logs
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: